window.addEventListener('error',e=>console.error('Application error:',e.error||e.message));
window.addEventListener('unhandledrejection',e=>console.error('Unhandled rejection:',e.reason));
let db={customers:[],loans:[],payments:[],dps:[],dpsPayments:[],expenses:[],incomes:[],settings:{business:'Smart Kisti Manager',phone:'',address:'',footer:'ধন্যবাদ',dailyTarget:0,theme:'dark'},logs:[]};
const $=id=>document.getElementById(id); const money=n=>'৳'+Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0}); const today=()=>new Date().toISOString().slice(0,10); const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function norm(){for(const k of ['customers','loans','payments','dps','dpsPayments','expenses','incomes','logs'])db[k]=Array.isArray(db[k])?db[k]:[];db.settings={business:'Smart Kisti Manager',phone:'',address:'',footer:'ধন্যবাদ',dailyTarget:0,theme:'dark',...(db.settings||{})}}
function log(action,detail=''){db.logs.unshift({id:uid('log'),date:new Date().toISOString(),action,detail});db.logs=db.logs.slice(0,500)}
async function save(){await window.desktop.save(db)}
function cust(id){return db.customers.find(x=>x.id===id)||{name:'Unknown',phone:''}} function loan(id){return db.loans.find(x=>x.id===id)}
function info(l){let ps=db.payments.filter(p=>p.loanId===l.id),paid=ps.reduce((a,p)=>a+Number(p.amount||0),0),total=Number(l.totalAmount||l.amount||0),count=Number(l.installments||l.totalInstallments||0),per=Number(l.installmentAmount|| (count?total/count:0)),due=Math.max(total-paid,0),start=new Date(l.startDate||today());let next=Math.min(Math.max(Math.floor(paid/(per||Infinity))+1,1),Math.max(count,1)),nextDate=new Date(start);nextDate.setDate(nextDate.getDate()+(next-1)*Number(l.intervalDays||7));let overdue=nextDate<new Date(today())&&due>0;return{paid,total,count,per,due,next,nextDate:nextDate.toISOString().slice(0,10),overdue}}
function sums(){let collection=db.payments.reduce((a,p)=>a+Number(p.amount||0),0),dps=db.dpsPayments.reduce((a,p)=>a+Number(p.amount||0),0),income=db.incomes.reduce((a,p)=>a+Number(p.amount||0),0),expense=db.expenses.reduce((a,p)=>a+Number(p.amount||0),0),outstanding=db.loans.reduce((a,l)=>a+info(l).due,0);return{collection,dps,income,expense,outstanding,net:collection+dps+income-expense}}
function table(head,rows){return `<table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}" class="empty">কোনো তথ্য নেই</td></tr>`}</tbody></table>`}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('title').textContent=document.querySelector(`.nav[data-page="${page}"]`)?.textContent.replace(/^[^ ]+ /,'')||'Dashboard';render();}
window.go=go;
function modal(title,html,onSubmit){$('modalBody').innerHTML=`<h2>${title}</h2><form id="mform" class="form">${html}<div class="actions"><button type="button" class="btn alt" onclick="closeModal()">Cancel</button><button class="btn">Save</button></div></form>`;$('modal').classList.add('show');$('mform').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));closeModal()}}
function closeModal(){$('modal').classList.remove('show')};window.closeModal=closeModal;
function render(){norm();const s=sums();$('sCustomers').textContent=db.customers.length;$('sCollection').textContent=money(s.collection);$('sOutstanding').textContent=money(s.outstanding);$('sExpense').textContent=money(s.expense);$('sNet').textContent=money(s.net);let target=Number(db.settings.dailyTarget||0),td=db.payments.filter(p=>String(p.date).slice(0,10)===today()).reduce((a,p)=>a+Number(p.amount||0),0),pct=target?Math.min(100,td/target*100):0;$('targetBar').style.width=pct+'%';$('targetText').textContent=`আজকের Target ${money(target)} • আদায় ${money(td)} • ${pct.toFixed(0)}%`;$('heroText').textContent=`আজ ${db.loans.filter(l=>info(l).nextDate===today()&&!info(l).overdue).length}টি Due • ${db.loans.filter(l=>info(l).overdue).length}টি Overdue • আজকের আদায় ${money(td)}`;renderChart();renderPriority();renderCustomers();renderLoans();renderDps();renderPayments();renderCollection();renderDue();renderSchedule();renderCashbook();renderLedger();renderAnalytics();renderReports();fillSettings();}
function renderChart(){let now=new Date(),a=[];for(let i=5;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7),v=db.payments.filter(p=>String(p.date).slice(0,7)===key).reduce((x,p)=>x+Number(p.amount||0),0);a.push({m:d.toLocaleDateString('en',{month:'short'}),v})}let mx=Math.max(1,...a.map(x=>x.v));$('chart').innerHTML=a.map(x=>`<div class="col"><span class="small">${money(x.v)}</span><div class="stick"><i style="height:${x.v/mx*100}%"></i></div><span class="small">${x.m}</span></div>`).join('')}
function renderPriority(){let arr=db.loans.map(l=>({l,i:info(l)})).filter(x=>x.i.overdue||x.i.nextDate===today()).sort((a,b)=>Number(b.i.due)-Number(a.i.due)).slice(0,6);$('priority').innerHTML=arr.length?table(['Customer','Account','Due','Status','Action'],arr.map(x=>`<tr><td>${esc(cust(x.l.customerId).name)}</td><td>${esc(x.l.accountNo||'—')}</td><td>${money(x.i.per)}</td><td><span class="badge ${x.i.overdue?'over':'due'}">${x.i.overdue?'OVERDUE':'DUE'}</span></td><td><button class="btn icon" onclick="collect('${x.l.id}')">৳ Collect</button></td></tr>`)): '<div class="empty">আজকের Priority Queue খালি 🎉</div>'}
function renderCustomers(){let q=($('search')?.value||'').toLowerCase();let arr=db.customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(q));$('customerTable').innerHTML=table(['Customer','Phone','Kisti','Outstanding','Action'],arr.map(c=>{let ls=db.loans.filter(l=>l.customerId===c.id),o=ls.reduce((a,l)=>a+info(l).due,0);return `<tr><td><b>${esc(c.name)}</b><div class="small">${esc(c.address||'')}</div></td><td>${esc(c.phone||'—')}</td><td>${ls.length}</td><td>${money(o)}</td><td><button class="btn icon" onclick="editCustomer('${c.id}')">✏</button> <button class="btn danger icon" onclick="delCustomer('${c.id}')">×</button></td></tr>`}))}
function renderLoans(){let arr=db.loans; $('loanTable').innerHTML=table(['Account','Customer','Total','Paid','Outstanding','Next Due','Status','Action'],arr.map(l=>{let i=info(l);return `<tr><td>${esc(l.accountNo||'—')}</td><td>${esc(cust(l.customerId).name)}</td><td>${money(i.total)}</td><td>${money(i.paid)}</td><td>${money(i.due)}</td><td>${i.nextDate}</td><td><span class="badge ${i.overdue?'over':i.due<=0?'paid':'due'}">${i.due<=0?'COMPLETED':i.overdue?'OVERDUE':'ACTIVE'}</span></td><td><button class="btn icon" onclick="collect('${l.id}')">৳</button> <button class="btn danger icon" onclick="delLoan('${l.id}')">×</button></td></tr>`}))}
function renderDps(){$('dpsTable').innerHTML=table(['Customer','Plan','Monthly','Deposited','Remaining','Action'],db.dps.map(d=>{let paid=db.dpsPayments.filter(p=>p.dpsId===d.id).reduce((a,p)=>a+Number(p.amount||0),0),total=Number(d.total||d.monthly||0)*Number(d.months||0);return `<tr><td>${esc(cust(d.customerId).name)}</td><td>${esc(d.plan||'DPS')}</td><td>${money(d.monthly)}</td><td>${money(paid)}</td><td>${money(Math.max(total-paid,0))}</td><td><button class="btn icon" onclick="dpsPay('${d.id}')">＋ Deposit</button></td></tr>`}))}
function renderPayments(){$('paymentTable').innerHTML=table(['Date','Customer','Account','Amount','Method','Note'],db.payments.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(cust(loan(p.loanId)?.customerId).name)}</td><td>${esc(loan(p.loanId)?.accountNo||'—')}</td><td>${money(p.amount)}</td><td>${esc(p.method||'Cash')}</td><td>${esc(p.note||'')}</td></tr>`))}
function renderCollection(){let rows=db.loans.map(l=>({l,i:info(l)})).filter(x=>x.i.overdue||x.i.nextDate===today());let due=rows.filter(x=>x.i.nextDate===today()&&!x.i.overdue).reduce((a,x)=>a+x.i.per,0),over=rows.filter(x=>x.i.overdue).reduce((a,x)=>a+x.i.per,0),col=db.payments.filter(p=>p.date===today()).reduce((a,p)=>a+Number(p.amount||0),0),target=Number(db.settings.dailyTarget||0);$('cDue').textContent=money(due);$('cOver').textContent=money(over);$('cCollected').textContent=money(col);$('cRate').textContent=(target?col/target*100:0).toFixed(0)+'%';$('collectionTable').innerHTML=table(['Priority','Customer','Phone','Due','Date','Action'],rows.map(x=>`<tr><td>${x.i.overdue?'🔴':'🟡'}</td><td>${esc(cust(x.l.customerId).name)}</td><td>${esc(cust(x.l.customerId).phone||'')}</td><td>${money(x.i.per)}</td><td>${x.i.nextDate}</td><td><button class="btn icon" onclick="collect('${x.l.id}')">৳ Collect</button> <button class="btn alt icon" onclick="whatsapp('${x.l.id}')">WA</button></td></tr>`))}
function renderDue(){let rows=db.loans.map(l=>({l,i:info(l)})).filter(x=>x.i.due>0);$('dueTable').innerHTML=table(['Customer','Account','Outstanding','Next Due','Days','Status'],rows.map(x=>{let days=Math.max(0,Math.floor((Date.now()-new Date(x.i.nextDate))/86400000));return `<tr><td>${esc(cust(x.l.customerId).name)}</td><td>${esc(x.l.accountNo||'')}</td><td>${money(x.i.due)}</td><td>${x.i.nextDate}</td><td>${days}</td><td><span class="badge ${x.i.overdue?'over':'due'}">${x.i.overdue?'OVERDUE':'UPCOMING'}</span></td></tr>`}))}
function renderSchedule(){let rows=[];db.loans.forEach(l=>{let i=info(l);for(let n=0;n<(i.count||0);n++){let d=new Date(l.startDate||today());d.setDate(d.getDate()+n*Number(l.intervalDays||7));let paid=n<Math.floor(i.paid/(i.per||1));rows.push(`<tr><td>${esc(cust(l.customerId).name)}</td><td>${esc(l.accountNo||'')}</td><td>${n+1}/${i.count}</td><td>${money(i.per)}</td><td>${d.toISOString().slice(0,10)}</td><td><span class="badge ${paid?'paid':d<new Date()?'over':'due'}">${paid?'PAID':d<new Date()?'OVERDUE':'DUE'}</span></td></tr>`)}});$('scheduleTable').innerHTML=table(['Customer','Account','Installment','Amount','Due Date','Status'],rows)}
function transactionRows(){let r=[];db.payments.forEach(p=>r.push({date:p.date,type:'Kisti Collection',in:+p.amount||0,out:0,detail:cust(loan(p.loanId)?.customerId).name,method:p.method||'Cash'}));db.dpsPayments.forEach(p=>r.push({date:p.date,type:'DPS Deposit',in:+p.amount||0,out:0,detail:cust(db.dps.find(d=>d.id===p.dpsId)?.customerId).name,method:p.method||'Cash'}));db.incomes.forEach(p=>r.push({date:p.date,type:'Other Income',in:+p.amount||0,out:0,detail:p.category||'Income',method:p.method||'Cash'}));db.expenses.forEach(p=>r.push({date:p.date,type:'Expense',in:0,out:+p.amount||0,detail:p.category||'Expense',method:p.method||'Cash'}));return r.sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function renderCashbook(){let r=transactionRows(),ci=r.reduce((a,x)=>a+x.in,0),co=r.reduce((a,x)=>a+x.out,0);$('cbIn').textContent=money(ci);$('cbOut').textContent=money(co);$('cbNet').textContent=money(ci-co);$('cbTx').textContent=r.length;$('cashTable').innerHTML=table(['Date','Type','Detail','Method','In','Out'],r.map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${esc(x.detail)}</td><td>${esc(x.method)}</td><td>${x.in?money(x.in):'—'}</td><td>${x.out?money(x.out):'—'}</td></tr>`))}
function renderLedger(){let sel=$('ledgerCustomer');if(!sel)return;let old=sel.value;sel.innerHTML='<option value="">গ্রাহক নির্বাচন করুন</option>'+db.customers.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone||'')}</option>`).join('');sel.value=old;let c=old;if(!c){$('ledgerSummary').innerHTML='';$('ledgerTable').innerHTML='<div class="empty">একজন Customer নির্বাচন করুন</div>';return}let ls=db.loans.filter(l=>l.customerId===c),ps=db.payments.filter(p=>ls.some(l=>l.id===p.loanId)),o=ls.reduce((a,l)=>a+info(l).due,0),paid=ps.reduce((a,p)=>a+Number(p.amount||0),0);$('ledgerSummary').innerHTML=`<div class="kpi"><small>Accounts</small><b>${ls.length}</b></div><div class="kpi"><small>Paid</small><b>${money(paid)}</b></div><div class="kpi"><small>Outstanding</small><b>${money(o)}</b></div><div class="kpi"><small>Transactions</small><b>${ps.length}</b></div>`;$('ledgerTable').innerHTML=table(['Date','Account','Amount','Method','Note'],ps.map(p=>`<tr><td>${p.date}</td><td>${esc(loan(p.loanId)?.accountNo||'')}</td><td>${money(p.amount)}</td><td>${esc(p.method||'Cash')}</td><td>${esc(p.note||'')}</td></tr>`))}
function renderAnalytics(){let r=transactionRows(),ci=r.reduce((a,x)=>a+x.in,0),co=r.reduce((a,x)=>a+x.out,0),over=db.loans.filter(l=>info(l).overdue).reduce((a,l)=>a+info(l).due,0);$('aIn').textContent=money(ci);$('aOut').textContent=money(co);$('aNet').textContent=money(ci-co);$('aOver').textContent=money(over);let methods={};db.payments.forEach(p=>methods[p.method||'Cash']=(methods[p.method||'Cash']||0)+Number(p.amount||0));let mx=Math.max(1,...Object.values(methods));$('methods').innerHTML=Object.entries(methods).map(([k,v])=>`<div class="barline"><span>${esc(k)}</span><div class="bar"><i style="width:${v/mx*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<div class="empty">Payment data নেই</div>';let ages=[0,0,0,0],av=[0,0,0,0];db.loans.forEach(l=>{let i=info(l);if(!i.overdue)return;let d=Math.floor((Date.now()-new Date(i.nextDate))/86400000),ix=d<=7?0:d<=30?1:d<=60?2:3;ages[ix]++;av[ix]+=i.due});$('aging').innerHTML=['1–7 দিন','8–30 দিন','31–60 দিন','61+ দিন'].map((k,i)=>`<div class="barline"><span>${k}</span><div class="bar"><i style="width:${Math.min(100,av[i]/Math.max(1,over)*100)}%"></i></div><b>${money(av[i])}</b></div>`).join('')}
function renderReports(){let s=sums();$('reportTitle').textContent=db.settings.business||'Business Report';$('reportMeta').textContent=`Generated ${new Date().toLocaleString()} • Smart Kisti Manager v26`;$('reportBody').innerHTML=table(['Metric','Value'],[['Customers',db.customers.length],['Kisti Collection',money(s.collection)],['DPS Deposit',money(s.dps)],['Other Income',money(s.income)],['Expense',money(s.expense)],['Outstanding',money(s.outstanding)],['Net Cash',money(s.net)]].map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td></tr>`))}
function fillSettings(){let f=$('settingsForm');if(!f)return;f.business.value=db.settings.business;f.phone.value=db.settings.phone;f.address.value=db.settings.address;f.footer.value=db.settings.footer;f.dailyTarget.value=db.settings.dailyTarget}
function addCustomer(){modal('নতুন Customer',`<label>নাম<input name="name" required></label><label>মোবাইল<input name="phone"></label><label>ঠিকানা<input name="address"></label>`,async f=>{db.customers.push({id:uid('c'),name:f.get('name'),phone:f.get('phone'),address:f.get('address')});log('Customer Added',f.get('name'));await save();render()})}
function editCustomer(id){let c=cust(id);modal('Customer Edit',`<label>নাম<input name="name" value="${esc(c.name)}" required></label><label>মোবাইল<input name="phone" value="${esc(c.phone)}"></label><label>ঠিকানা<input name="address" value="${esc(c.address)}"></label>`,async f=>{Object.assign(c,{name:f.get('name'),phone:f.get('phone'),address:f.get('address')});log('Customer Updated',c.name);await save();render()})}
async function delCustomer(id){if(!confirm('Customer delete করবেন?'))return;db.customers=db.customers.filter(x=>x.id!==id);log('Customer Deleted',id);await save();render()}
function addLoan(){if(!db.customers.length)return toast('আগে Customer যোগ করুন');modal('নতুন Kisti Account',`<label>Customer<select name="customerId" required>${db.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><div class="two"><label>Account No<input name="accountNo" value="KST-${Date.now().toString().slice(-6)}"></label><label>Total Amount<input name="totalAmount" type="number" min="0" required></label></div><div class="two"><label>Installments<input name="installments" type="number" value="12" min="1"></label><label>Interval Days<input name="intervalDays" type="number" value="7" min="1"></label></div><label>Start Date<input name="startDate" type="date" value="${today()}"></label>`,async f=>{let total=+f.get('totalAmount'),count=+f.get('installments');db.loans.push({id:uid('l'),customerId:f.get('customerId'),accountNo:f.get('accountNo'),totalAmount:total,installments:count,intervalDays:+f.get('intervalDays'),startDate:f.get('startDate'),installmentAmount:count?total/count:0});log('Kisti Account Added',f.get('accountNo'));await save();render()})}
async function delLoan(id){if(!confirm('Kisti account delete করবেন?'))return;db.loans=db.loans.filter(x=>x.id!==id);db.payments=db.payments.filter(x=>x.loanId!==id);log('Kisti Account Deleted',id);await save();render()}
function collect(id){let l=loan(id),i=info(l);modal('Payment Collection',`<div class="note"><b>${esc(cust(l.customerId).name)}</b> • ${esc(l.accountNo||'')} • Suggested ${money(i.per)}</div><label>Amount<input name="amount" type="number" value="${Math.min(i.per,i.due)}" min="0" required></label><div class="two"><label>Date<input name="date" type="date" value="${today()}"></label><label>Method<select name="method"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Bank</option><option>Other</option></select></label></div><label>Note<input name="note"></label>`,async f=>{db.payments.push({id:uid('p'),loanId:id,amount:+f.get('amount'),date:f.get('date'),method:f.get('method'),note:f.get('note')});log('Payment Added',`${l.accountNo} ${f.get('amount')}`);await save();render()})}
function addDps(){if(!db.customers.length)return toast('আগে Customer যোগ করুন');modal('নতুন DPS',`<label>Customer<select name="customerId">${db.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><div class="two"><label>Plan<input name="plan" value="DPS-01"></label><label>Monthly Amount<input name="monthly" type="number" value="1000"></label></div><label>Months<input name="months" type="number" value="12"></label>`,async f=>{db.dps.push({id:uid('d'),customerId:f.get('customerId'),plan:f.get('plan'),monthly:+f.get('monthly'),months:+f.get('months')});log('DPS Added',f.get('plan'));await save();render()})}
function dpsPay(id){let d=db.dps.find(x=>x.id===id);modal('DPS Deposit',`<label>Amount<input name="amount" type="number" value="${d.monthly}"></label><div class="two"><label>Date<input name="date" type="date" value="${today()}"></label><label>Method<select name="method"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Bank</option></select></label></div>`,async f=>{db.dpsPayments.push({id:uid('dp'),dpsId:id,amount:+f.get('amount'),date:f.get('date'),method:f.get('method')});log('DPS Deposit Added',d.plan);await save();render()})}
function addExpense(){modal('নতুন Expense',`<div class="two"><label>Category<input name="category" value="Office"></label><label>Amount<input name="amount" type="number" min="0"></label></div><div class="two"><label>Date<input name="date" type="date" value="${today()}"></label><label>Method<select name="method"><option>Cash</option><option>bKash</option><option>Bank</option></select></label></div><label>Note<input name="note"></label>`,async f=>{db.expenses.push({id:uid('e'),category:f.get('category'),amount:+f.get('amount'),date:f.get('date'),method:f.get('method'),note:f.get('note')});log('Expense Added',f.get('category'));await save();render()})}
function whatsapp(id){let l=loan(id),c=cust(l.customerId),i=info(l);let msg=`আসসালামু আলাইকুম ${c.name}, আপনার কিস্তি ${money(i.per)} এর Due ${i.nextDate}। Smart Kisti Manager`;location.href='https://wa.me/'+String(c.phone||'').replace(/\D/g,'')+'?text='+encodeURIComponent(msg)}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',1800)}
$('addCustomer').onclick=addCustomer;$('addLoan').onclick=addLoan;$('addDps').onclick=addDps;$('quickPay').onclick=()=>db.loans[0]?collect(db.loans[0].id):toast('আগে Kisti Account যোগ করুন');$('qaCustomer').onclick=addCustomer;$('qaLoan').onclick=addLoan;$('qaDps').onclick=addDps;$('qaExpense').onclick=addExpense;$('search').oninput=renderCustomers;$('ledgerCustomer').onchange=renderLedger;$('close').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('backup').onclick=async()=>{let r=await window.desktop.backup(db);if(r)toast('Backup saved')};$('restore').onclick=async()=>{let d=await window.desktop.restore();if(d){db=d;norm();await save();render();toast('Restored')}};$('openFolder').onclick=()=>window.desktop.openFolder();$('theme').onclick=async()=>{db.settings.theme=db.settings.theme==='dark'?'light':'dark';applyTheme();await save()};$('settingsForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget);Object.assign(db.settings,{business:f.get('business'),phone:f.get('phone'),address:f.get('address'),footer:f.get('footer'),dailyTarget:+f.get('dailyTarget')||0});log('Settings Updated','Business settings');await save();render();toast('Settings saved')};$('savePdf').onclick=async()=>{let r=await window.desktop.savePDF();if(r)toast('PDF saved')};['printPayments','printCollection','printDue','printSchedule','printCashbook','printLedger','printAnalytics','printReport'].forEach(id=>$(id).onclick=()=>window.print());
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));
(async()=>{db=await window.desktop.load();norm();applyTheme();render()})();function applyTheme(){document.documentElement.classList.toggle('light',db.settings.theme==='light')}
